[package]
name = "nekroctl-gui-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
serde = { version = "1.0", features = ["derive"] }
poll-promise = "0.3"
egui_extras = "0.33.3"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
